namespace: default
cortxdataprov:
  name: cortx-data-prov-pod
  image: ghcr.io/seagate/centos:7
  nodename: node-1
  mountblkinfo: mnt-blk-info.txt
  secretinfo: secret-info.txt
  serviceaccountname: cortx-sa
  service:
    clusterip:
      name: cortx-data-clusterip-svc
    headless:
      name: cortx-data-headless-svc
  cfgmap:
    mountpath: /etc/cortx/solution
    volmountname: config001
    name: cortx-provisioner-cfgmap
  sslcfgmap:
    mountpath: /etc/cortx/solution/ssl
    volmountname: ssl-config001
    name: cortx-ssl-cert-cfgmap
  machineid:
    mountpath: /etc/cortx/solution/node
    volmountname: machine-id-config
    name:  cortx-data-machine-id-cfgmap
  localpathpvc:
    name: cortx-fs-local-pvc
    mountpath: /etc/cortx # This is the mount path in the container
    requeststoragesize: 1Gi