cluster:
  name: cortx-cluster
  id: <<.Values.cortx.cluster.id>>
  node_types:
  - name: storage_node
    components:
    - name: utils
    - name: motr
      services:
      - io
    - name: hare
    - name: s3
      services:
      - io
      - auth
      - bg_consumer
    storage:
    - name: cvg-01
      type: ios
      devices:
        metadata:
        - /dev/sdb
        data:
        - /dev/sdc
        - /dev/sdd
    - name: cvg-02
      type: ios
      devices:
        metadata:
        - /dev/sdf
        data:
        - /dev/sdg
        - /dev/sdh
  - name: control_node
    components:
    - name: utils
    - name: motr
      services:
      - fsm
    - name: s3
      services:
      - bg_producer
      - openldap
    - name: csm
      services:
      - agent
  storage_sets:
  - name: storage-set-1
    durability:
      sns: 8+7+0
      dix: 1+0+0
    nodes:
    <<.Values.cluster.storage_sets.nodes>>
