cluster:
  name: cortx-cluster
  id: <<.Values.cortx.cluster.id>>
  node_types:
  - name: storage_node
    components:
    - name: motr
      services:
      - io
    - name: hare
    - name: s3
      services:
      - io
      - auth
      - bg_consumer
    - name: utils
      services:
      - message_bus
    storage:
    - name: cvg-01
      type: ios
      devices:
        metadata: /dev/sda
        data:
        - /dev/sdb
        - /dev/sdc
    - name: cvg-02
      type: cas
      devices:
        log: /dev/sdh
        meta0: /dev/sdj
        metadata: /dev/sdk
        data:
          - /dev/sdx
          - /dev/sdy
  - name: control_node
    components:
    - name: csm
      services:
      - agent
    - name: motr
      services:
      - fsm
    - name: s3
      services:
      - bg_producer
  storage_sets:
  - name: storage-set-1
    durability:
      sns: 8+7+0
      dix: 1+7+0
    nodes:
      <<.Values.cluster.storage_sets.nodes>>
