cortx:
  external:
    kafka:
      endpoints:
        - tcp://kafka.default.svc.cluster.local:9092
      admin: admin
      secret: kafka_admin_secret
    openldap:
      endpoints:
        - ldap://openldap-svc.default.svc.cluster.local:389
        - ssl://openldap-svc.default.svc.cluster.local:636
      servers:
        - openldap-svc.default.svc.cluster.local
      admin: admin
      secret: openldap_admin_secret
      base_dn: dc=seagate,dc=com
    consul:
      endpoints:
        - tcp://consul-server.default.svc.cluster.local:8301
      admin: admin
      secret: consul_admin_secret
  common:
    product_release: LC
    environment_type: K8
    setup_size: small
    service:
      admin: admin
      secret: common_admin_secret
    storage:
      shared: <<.Values.cortx.common.storage.shared>>
      local: <<.Values.cortx.common.storage.local>>
      log: <<.Values.cortx.common.storage.log>>
      config: <<.Values.cortx.common.storage.local>>
    security:
      ssl_certificate: /etc/cortx/solution/ssl/s3.seagate.com.pem
      domain_certificate: /etc/cortx/solution/ssl/stx.pem
      device_certificate: /etc/cortx/solution/ssl/stx.pem
  utils:
    message_bus_backend: kafka
  s3:
    iam:
      endpoints:
      - https://<<.Values.cortx.data.svc>>:9443
      - http://<<.Values.cortx.data.svc>>:9080
    data:
      endpoints:
      - http://<<.Values.cortx.data.svc>>:80
      - https://<<.Values.cortx.data.svc>>:443
    internal:
      endpoints:
      - http://<<.Values.cortx.data.svc>>:28049
    service_instances: <<.Values.cortx.num_s3_inst>>
    io_max_units: 8
    auth_admin: sgiamadmin
    auth_secret: s3_auth_admin_secret
  motr:
    client_instances: <<.Values.cortx.num_motr_inst>>
    interface_type: tcp
    interface_family: inet
    transport_type: libfab
    ios:
      endpoints:
      - motr://<<.Values.cortx.data.svc>>:3232
  hare:
    hax:
      endpoints:
      - tcp://<<.Values.cortx.data.svc>>:28000
  csm:
    auth_admin: authadmin
    auth_secret: csm_auth_admin_secret
    mgmt_admin: cortxadmin
    mgmt_secret: csm_mgmt_admin_secret
    email_address: cortx@seagate.com
    agent:
      endpoints:
      - https://<<.Values.cortx.data.svc>>:8081
