namespace: default
cortxcontrolprov:
  name: cortx-control-prov-pod
  service:
    clusterip:
      name: cortx-control-clusterip-svc
    headless:
      name: cortx-control-headless-svc
  cfgmap:
    mountpath: /etc/cortx
    volmountname: config001
    name: cortx-provisioner-cfgmap
  localpathpvc:
    name: cortx-fs-local-pvc
    mountpath: /data # This is the mount path in the container
    requeststoragesize: 1Gi
cortxgluster:
  pv:
    name: gluster-default-volume
    mountpath: /mnt/fs-local-volume/etc/gluster/test_folder/ # This is the mount path in the container
  pvc:
    name: gluster-claim