apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cortxcontrol.service.messageserver.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: cortx-message-server-28300
      port: 28300
      targetPort: 28300
      protocol: TCP
  selector:
    app: {{ .Values.cortxcontrol.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cortxcontrol.service.headless.name }}
  namespace: {{ .Values.namespace }}
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: {{ .Values.cortxcontrol.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cortxcontrol.service.loadbal.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.cortxcontrol.name }}
  ports:
  - name: cotrx-control-8081
    port: 8081
    targetPort: 8081
    nodePort: 31169