apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cortxcontrol.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.cortxcontrol.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.cortxcontrol.name }}
    spec:
      volumes:
        - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
          configMap:
            name: {{ .Values.cortxcontrol.cfgmap.name }}  
        - name: {{ .Values.cortxgluster.pv.name }}
          persistentVolumeClaim:
              claimName: {{ .Values.cortxgluster.pvc.name }}
        - name: local-path-pv
          persistentVolumeClaim:
            claimName: {{ .Values.cortxcontrol.localpathpvc.name }}            
      containers:
        - name: cortx-free-space-monitor
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeMounts:
            - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxcontrol.cfgmap.mountpath }}
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxcontrol.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxcontrol.name }}
        - name: cortx-bg-producer
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeMounts:
            - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxcontrol.cfgmap.mountpath }}
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxcontrol.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxcontrol.name }}
          ports:
          - containerPort: 28049
        - name: cortx-csm-agent
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeMounts:
            - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxcontrol.cfgmap.mountpath }}
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxcontrol.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxcontrol.name }}
          ports:
          - containerPort: 28101
        - name: cortx-liveness-probe
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeMounts:
            - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxcontrol.cfgmap.mountpath }}
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxcontrol.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxcontrol.name }}
          ports:
          - containerPort: 5152

# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: {{ .Values.cortxcontrol.name }}
#   labels:
#     app.kubernetes.io/name: {{ .Values.cortxcontrol.name }}
# spec:
#   serviceName: {{ .Values.cortxcontrol.service.name }}
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: {{ .Values.cortxcontrol.name }}
#   replicas: 2
#   template:
#     metadata:
#       labels:
#         app.kubernetes.io/name: {{ .Values.cortxcontrol.name }}
#     spec:
#       volumes:
#         - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
#           configMap:
#             name: {{ .Values.cortxcontrol.cfgmap.name }}  
#         - name: gluster-default-volume
#           persistentVolumeClaim:
#               claimName: gluster-claim
#         # - name: cortx-fs-local-pvc-node-1
#         #   persistentVolumeClaim:
#         #     claimName: {{ .Values.cortxcontrol.localpathpvc.name }}
#       containers:
#         - name: container001
#           image: centos:7
#           imagePullPolicy: IfNotPresent
#           command: ["/bin/sleep", "3650d"]
#           env:
#             - name: UDS_CLOUD_CONTAINER_NAME
#               value: {{ .Values.cortxcontrol.name }}
#           ports:
#           - containerPort: 5151
#           volumeMounts:
#             - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
#               mountPath: {{ .Values.cortxcontrol.cfgmap.mountpath }}
#             - name: gluster-default-volume
#               mountPath: /mnt/fs-local-volume/etc/gluster/test_folder/
#             - name: cortx-control-fs-local-pvc
#               mountPath: /data
#             # - name: cortx-fs-local-pvc-node-1
#             #   mountPath: /data
#         - name: container002
#           image: centos:7
#           imagePullPolicy: IfNotPresent
#           command: ["/bin/sleep", "3650d"]
#           env:
#             - name: UDS_CLOUD_CONTAINER_NAME
#               value: {{ .Values.cortxcontrol.name }}
#           ports:
#           - containerPort: 5151
#           volumeMounts:
#             - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
#               mountPath: {{ .Values.cortxcontrol.cfgmap.mountpath }}
#             - name: gluster-default-volume
#               mountPath: /mnt/fs-local-volume/etc/gluster/test_folder/
#             - name: cortx-control-fs-local-pvc
#               mountPath: /data
#             # - name: cortx-fs-local-pvc-node-1
#             #   mountPath: /data
#   volumeClaimTemplates:
#     - metadata:
#         name: cortx-control-fs-local-pvc
#       spec:
#         accessModes: 
#           - ReadWriteOnce
#         resources:
#           requests:
#             storage: 1Gi
#         storageClassName: local-path