apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.cortxprov.name }}
  namespace: {{ .Values.namespace }}
spec:
  volumes:
    - name: {{ .Values.cortxprov.cfgmap.volmountname }}
      configMap:
        name: {{ .Values.cortxprov.cfgmap.name }}
    {{- $nodename := (.Values.cortxprov.nodename) }}
    {{- range .Files.Lines .Values.cortxprov.mountblkinfo }}
    {{- $basepath := (base .) }}
    - name: {{ printf "cortx-data-%s-pv-%s" $basepath $nodename }}
      persistentVolumeClaim:
        claimName: {{ printf "cortx-data-%s-pvc-%s" $basepath $nodename }}
    {{- end }}
    - name: {{ .Values.cortxgluster.pv.name }}
      persistentVolumeClaim:
        claimName: {{ .Values.cortxgluster.pvc.name }}
    - name: local-path-pv
      persistentVolumeClaim:
        claimName: {{ .Values.cortxprov.localpathpvc.name }}
  containers:
  - name: container1
    image: centos:7
    imagePullPolicy: IfNotPresent        
    command: 
      - /bin/sh
    args: 
      - -c
      - sleep $(shuf -i 5-10 -n 1)s
    volumeDevices:
      {{- range .Files.Lines .Values.cortxprov.mountblkinfo }}
      - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
        devicePath: {{ . }}
      {{- end }}
    volumeMounts:
      - name: {{ .Values.cortxprov.cfgmap.volmountname }}
        mountPath: {{ .Values.cortxprov.cfgmap.mountpath }}
      - name: {{ .Values.cortxgluster.pv.name }}
        mountPath: {{ .Values.cortxgluster.pv.mountpath }}
      - name: local-path-pv
        mountPath: {{ .Values.cortxprov.localpathpvc.mountpath }}
  restartPolicy: Never
