apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.cortxprov.localpathpvc.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi