apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulset.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.statefulset.name }}
spec:
  serviceName: {{ .Values.service.name }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.statefulset.name }}
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.statefulset.name }}
    spec:
      containers:
        - name: {{ .Values.statefulset.name }}
          image: localhost:5000/cortx-openldap:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          ports:
            - name: tcp-ldap
              containerPort: 389
          volumeMounts:
            - name: openldap-data
              mountPath: /var/lib/ldap
  volumeClaimTemplates:
  - metadata:
      name: openldap-data
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: {{ .Values.storageclass }}
      resources:
        requests:
          storage: {{ .Values.storagesize }}