{{- if .Values.networkPolicy.create -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.namePrefix }}cortx-s3-haproxy
  labels:
    source-pod: cortx-data
    target-pod: cortx-data
    target-container: cortx-s3-haproxy
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      name: {{ .Values.networkPolicy.cortxData.podNameLabel }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.cortxData.podNameLabel }}
    ports:
      - protocol: TCP
        port: 80
      - protocol: TCP
        port: 443
      - protocol: TCP
        port: 9080
      - protocol: TCP
        port: 9443
      - protocol: TCP
        port: 28049

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.namePrefix }}cortx-s3
  labels:
    source-pod: cortx-data
    target-pod: cortx-data
    target-container: cortx-s3
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      name: {{ .Values.networkPolicy.cortxData.podNameLabel }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.cortxData.podNameLabel }}
    ports:
      - protocol: TCP
        port: 28051
      - protocol: TCP
        port: 28052

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.namePrefix }}cortx-motr-ios
  labels:
    source-pod: cortx-data
    target-pod: cortx-data
    target-container: cortx-motr-ios
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      name: {{ .Values.networkPolicy.cortxData.podNameLabel }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.cortxData.podNameLabel }}
    ports:
      - protocol: TCP
        port: 29000
      - protocol: TCP
        port: 29001

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.namePrefix }}cortx-control
  labels:
    source-pod: cortx-control
    target-pod: cortx-data
    target-container: cortx-s3-bg-consumer
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      name: {{ .Values.networkPolicy.cortxData.podNameLabel }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.networkPolicy.cortxControl.podAppLabel }}
    ports:
      - protocol: TCP
        port: 28049 

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.namePrefix }}cortx-data-misc
  labels:
    source-pod: cortx-data
    target-pod: cortx-data
    target-container: misc
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      name: {{ .Values.networkPolicy.cortxData.podNameLabel }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.cortxData.podNameLabel }}
    ports:
      - protocol: TCP
        port: 2001
      - protocol: TCP
        port: 3001
      - protocol: TCP
        port: 3002
      - protocol: TCP
        port: 3003      
      - protocol: TCP
        port: 4001      
      - protocol: TCP
        port: 4002

{{- end }}