{{- range $line := .Files.Lines .Values.openldap.nodelistinfo }}
{{ $parts := split " " . }}
{{- $index := $parts._0 }}
{{- $nodename := $parts._1 }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "etc-cortx-%s" $index }}
spec:
  storageClassName: {{ $.Values.openldap.storageclass }}
  capacity:
    storage: {{ $.Values.openldap.storagesize }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: {{ printf "etc-cortx-openldap-%s" $index }}
  local:
    path: /etc/cortx
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ printf "%s" $nodename }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "var-data-cortx-%s" $index }}
spec:
  storageClassName: {{ $.Values.openldap.storageclass }}
  capacity:
    storage: {{ $.Values.openldap.storagesize }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: {{ printf "var-data-cortx-openldap-%s" $index }}
  local:
    path: /var/data/cortx
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ printf "%s" $nodename }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "var-log-cortx-%s" $index }}
spec:
  storageClassName: {{ $.Values.openldap.storageclass }}
  capacity:
    storage: {{ $.Values.openldap.storagesize }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: {{ printf "var-log-cortx-openldap-%s" $index }}
  local:
    path: /var/log/cortx
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ printf "%s" $nodename }}
---
{{- end }}
