apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv1.name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.storageclass }}
  capacity:
    storage: {{ .Values.storagesize }}
  accessModes:
    - ReadWriteMany
  local:
    path: {{ .Values.pv1.localpath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - {{ .Values.pv1.node }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv2.name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.storageclass }}
  capacity:
    storage: {{ .Values.storagesize }}
  accessModes:
    - ReadWriteMany
  local:
    path: {{ .Values.pv2.localpath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - {{ .Values.pv2.node }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv3.name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.storageclass }}
  capacity:
    storage: {{ .Values.storagesize }}
  accessModes:
    - ReadWriteMany
  local:
    path: {{ .Values.pv3.localpath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - {{ .Values.pv3.node }}