apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cortxdata.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.cortxdata.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.cortxdata.name }}
    spec:
      volumes:
        - name: {{ .Values.cortxdata.cfgmap.volmountname }}
          configMap:
            name: {{ .Values.cortxdata.cfgmap.name }}
        {{- $nodename := (.Values.cortxdata.nodename) }}
        {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
        {{- $basepath := (base .) }}
        - name: {{ printf "cortx-data-%s-pv-%s" $basepath $nodename }}
          persistentVolumeClaim:
            claimName: {{ printf "cortx-data-%s-pvc-%s" $basepath $nodename }}
        {{- end }}
        - name: {{ .Values.cortxgluster.pv.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.cortxgluster.pvc.name }}
        - name: local-path-pv
          persistentVolumeClaim:
            claimName: {{ .Values.cortxdata.localpathpvc.name }}
      containers:
        - name: cortx-s3-server
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxdata.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
          ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 9080
          - containerPort: 9443
        - name: cortx-s3-auth-server
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxdata.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
          ports:
          - containerPort: 28050
        - name: cortx-motr-hax
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxdata.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
        - name: cortx-motr-io-cas
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxdata.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
        - name: cortx-motr-confd
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxdata.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
        - name: cortx-consul-agent
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxdata.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
          ports:
          - containerPort: 8500
        - name: cortx-s3-bg-consumer
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxdata.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
          ports:
          - containerPort: 28049
        - name: cortx-message-svc
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxdata.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
        - name: cortx-liveness-probe
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxdata.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
          ports:
          - containerPort: 5051