apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cortxdata.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.cortxdata.name }}
  ports:
    - name: cortx-s3-server001-tcp
      protocol: TCP
      port: 80
      targetPort: 80
    - name: cortx-s3-server002-tcp
      protocol: TCP
      port: 443
      targetPort: 443
    - name: cortx-s3-iam001-tcp
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: cortx-s3-iam002-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
    - name: cortx-s3-auth-server-tcp
      protocol: TCP
      port: 28050
      targetPort: 28050
    - name: cortx-consul-agent-tcp
      protocol: TCP
      port: 8500
      targetPort: 8500
    - name: cortx-s3-bg-consumer-tcp
      protocol: TCP
      port: 28049
      targetPort: 28049
    - name: cortx-liveness-probe-tcp
      protocol: TCP
      port: 5051
      targetPort: 5051