apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cortxdata.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.cortxdata.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.cortxdata.name }}
    spec:
      volumes:
        - name: {{ .Values.cortxdata.cfgmap.ctr1.volmountname }}
          configMap:
            name: {{ .Values.cortxdata.cfgmap.ctr1.name }}
        - name: {{ .Values.cortxdata.cfgmap.ctr2.volmountname }}
          configMap:
            name: {{ .Values.cortxdata.cfgmap.ctr2.name }}
        - name: {{ .Values.cortxdata.cfgmap.ctr3.volmountname }}
          configMap:
            name: {{ .Values.cortxdata.cfgmap.ctr3.name }}
        - name: {{ .Values.cortxdata.cfgmap.ctr4.volmountname }}
          configMap:
            name: {{ .Values.cortxdata.cfgmap.ctr4.name }}
        - name: {{ .Values.cortxdata.cfgmap.ctr5.volmountname }}
          configMap:
            name: {{ .Values.cortxdata.cfgmap.ctr5.name }}
        - name: {{ .Values.cortxdata.cfgmap.ctr6.volmountname }}
          configMap:
            name: {{ .Values.cortxdata.cfgmap.ctr6.name }}
        - name: {{ .Values.cortxdata.cfgmap.ctr7.volmountname }}
          configMap:
            name: {{ .Values.cortxdata.cfgmap.ctr7.name }}
        - name: {{ .Values.cortxdata.cfgmap.ctr8.volmountname }}
          configMap:
            name: {{ .Values.cortxdata.cfgmap.ctr8.name }}
        - name: {{ .Values.cortxdata.cfgmap.ctr9.volmountname }}
          configMap:
            name: {{ .Values.cortxdata.cfgmap.ctr9.name }}
        {{- $nodename := (.Values.cortxdata.nodename) }}
        {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
        {{- $basepath := (base .) }}
        - name: {{ printf "cortx-data-%s-pv-%s" $basepath $nodename }}
          persistentVolumeClaim:
            claimName: {{ printf "cortx-data-%s-pvc-%s" $basepath $nodename }}
        {{- end }}
        - name: {{ .Values.cortxgluster.pv.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.cortxgluster.pvc.name }}
        - name: local-path-pv
          persistentVolumeClaim:
            claimName: {{ .Values.cortxdata.localpathpvc.name }}
      containers:
        - name: container001
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: {{ .Values.cortxdata.cfgmap.ctr1.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: local-path-pv
              mountPath: /data
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
          ports:
          - containerPort: 5051
        - name: container002
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: {{ .Values.cortxdata.cfgmap.ctr2.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
          ports:
          - containerPort: 5052
        - name: container003
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: {{ .Values.cortxdata.cfgmap.ctr3.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
          ports:
          - containerPort: 5053
        - name: container004
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: {{ .Values.cortxdata.cfgmap.ctr4.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
          ports:
          - containerPort: 5054
        - name: container005
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: {{ .Values.cortxdata.cfgmap.ctr5.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
          ports:
          - containerPort: 5055
        - name: container006
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: {{ .Values.cortxdata.cfgmap.ctr6.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
          ports:
          - containerPort: 5056
        - name: container007
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: {{ .Values.cortxdata.cfgmap.ctr7.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
          ports:
          - containerPort: 5057
        - name: container008
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: {{ .Values.cortxdata.cfgmap.ctr8.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
          ports:
          - containerPort: 5058
        - name: container009
          image: centos:7
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          volumeDevices:
            {{- range .Files.Lines .Values.cortxdata.mountblkinfo }}
            - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
              devicePath: {{ . }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxgluster.pv.name }}
              mountPath: {{ .Values.cortxgluster.pv.mountpath }}
            - name: {{ .Values.cortxdata.cfgmap.ctr9.volmountname }}
              mountPath: {{ .Values.cortxdata.cfgmap.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxdata.localpathpvc.mountpath }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxdata.name }}
          ports:
          - containerPort: 5059