apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.cortxgluster.storageclass }}
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer