apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.cortxgluster.pvc.name }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.cortxgluster.storageclass }}
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: {{ .Values.cortxgluster.storagesize }}    