apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cortxsupport.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.cortxsupport.name }}
  ports:
    - name: cortx-support001-tcp
      protocol: TCP
      port: 5250
      targetPort: 5250